// Code generated by hertz generator.

package main

import (
	"judgeMore/biz/dal"
	"judgeMore/biz/mw/jwt"
	"judgeMore/biz/router"
	"judgeMore/biz/service"
	"judgeMore/config"
	"judgeMore/pkg/utils"

	"github.com/bytedance/gopkg/util/logger"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
)

func init() {
	config.Init("main")
	dal.Init()
	jwt.Init()
	service.Init()
}
func main() {
	listenAddr, err := utils.GetAvailablePort()
	if err != nil {
		logger.Fatalf("get available port failed, err: %v", err)
	}
	h := server.New(
		server.WithHostPorts(listenAddr),
		server.WithHandleMethodNotAllowed(true),
	)

	h.Use(cors.New(cors.Config{
		AllowOrigins:  []string{"*"},
		AllowMethods:  []string{"*"},
		AllowHeaders:  []string{"*"},
		ExposeHeaders: []string{"Access-Token", "Refresh-Token"},
		MaxAge:        86400,
		AllowWildcard: true,
	}))

	router.GeneratedRegister(h)
	h.Spin()
}
